version: "3.9"

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: webops_rails:latest 
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/WebOps-/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: webops
    ports: 
      - '5432:5432'
    volumes:
      - webops-postgres:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    command: ["--bind", "0.0.0.0"]
    ports:
      - '6379:6379'
    volumes:
      - webops-redis:/data

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq 
    volumes:
      - .:/WebOps-/app
    links:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  webops-postgres:
  webops-redis:
